server {
    listen 80;
    server_name _;

    location /feeds/ {
        alias /usr/share/nginx/html/feeds/;
        autoindex on;
        default_type application/json;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "no-store";
    }

    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}
